name: Omop_On_FHIR_Workflow
on:
  push:
    branches:
    - main
  pull_request:
env:
  TAG: 1.0.0
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker image
      run:  docker build -t omoponfhir . 

    - name: Create Network
      run:  docker run --name omoponfhir --network=omop -p 8080:8080 -d omoponfhir:latest

