name: Omop_On_FHIR_DB
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Install Database
        default: v1.0.0
        required: true
env:
  TAG: 1.0.0
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Pull Postgres docker image
      id: pull_postgress
      run:  docker pull postgres 
    
    - name: Run docker image
      id: run_postgres
      run:  docker run --name omop_v6 -p 5432:5432 -e POSTGRES_PASSWORD=${{secrets.JDBC_PASSWORD}} -d ${{secrets.JDBC_USERNAME}}
      continue-on-error: true

